### ISSUE TITLE
Generated codes aren't recognized (error correction L)

### ISSUE THREAD

**Issue by ezeaguerre** [rvillemeur/QRCode#1] opened 2022-05-23 20:19 UTC
Hi! I was using this to generate some QR codes but my cellphone (Android, tried many different apps) doesn't recognize the code.

After some investigation it turns out that if I choose an error correction level greater than 'L' then it is recognized. After some more experiments it turns out that if I force the encoding to UTF-8 (instead of ISO 8859-1) the codes are recognized (even for error correction level 'L').

I was doing something like this to generate the QR code:

```smalltalk
QRCodeEncoder codeForString: 'https://www.example.com/some/site' errorCorrection: $L eci: 26
```

Then that was turned into a form and displayed on the screen. But the problem was that an exception is raised due to `string` being `nil` in `QRCodeEncoder`. So I changed the `initializeEncoding` a little bit. From this:

```smalltalk
QRCodeEncoder>>initializeEncoding
  | index |
  code eci ifNotNil: [
    code encoding: #byte.
    ^ self ].
  string := code string.
  string isEmpty ...
```

To this:

```smalltalk
QRCodeEncoder>>initializeEncoding
  | index |
  string := code string. "Now 'string' gets initialized"
  code eci ifNotNil: [
    code encoding: #byte.
    ^ self ].
  string isEmpty ...
```

And now it works. I can generate QR codes with error correction level 'L' and they're recognized by my phone (for example with "QR Droid").

Thanks!

**Comment by rvillemeur** [comment] 2023-10-28 18:48
Thanks, the issue is now fixed, and  unit test associated to UTF8 encoding is fixed as well

**Closed as completed by rvillemeur** 2023-10-28 18:48 UTC

**Comment by ezeaguerre** [comment] 2023-10-31 20:00
Awesome! Thanks! :-)
